### ISSUE TITLE
Crashes when installing inside Docker using Bootsnap, Errno::ENOENT: No such file or directory - bs_fetch:open_current_file:open

### ISSUE THREAD

**Issue by parse** [graphiti-api/vandal_ui#3]
My setup consists of two apps, one `web` and one `api` using docker-compose.yml.

When trying to install Vandal inside my Docker, it crashes. See below for command and output: 

```
parse (parse/block-sort) $ docker-compose run api bundle exec rake vandal:install
Starting besep_db_1 ... done
rake aborted!
Errno::ENOENT: No such file or directory - bs_fetch:open_current_file:open
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/compile_cache/yaml.rb:49:in `fetch'
/usr/local/bundle/gems/bootsnap-1.3.2/lib/bootsnap/compile_cache/yaml.rb:49:in `block in install!'
/usr/local/bundle/gems/vandal_ui-0.4.2/lib/vandal_ui/tasks.rb:3:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => vandal:install
(See full trace by running task with --trace)
```

**Comment by richmolj** [comment]
The line of code that's breaking is

`YAML.load_file("#{Rails.root}/.graphiticfg.yml")`

This file is created when running the application template. Maybe you didn't use the template, or something about bootsnap/docker causing the file not to be seen?

**Comment by geeosh** [comment]
This happened to me as well, as I was adding this to an existing app. I created my own `.graphiticfg.yml` file with a `namespace` attribute, and it worked. Might be worth at least `touch` ing the file if it doesn't exist in the rake task. I can add a PR if you'd like.

**Comment by richmolj** [comment]
@geeosh that would be fantastic, thanks! I wonder if we should just raise an expressive error, maybe pointing to some docs on `.graphiticfg.yml`?

**Comment by geeosh** [comment]
@richmolj yeah so I think we'd need to add something in the docs, because I didn't encounter anything about `.graphiticfg.yml` when running through the installation instructions, as I was adding to an existing app.

So we could suggest that people add it as part of a typical installation, or auto-create it for them. Which would you prefer  (Or both)?

**Comment by richmolj** [comment]
At this point I would say let's add to [these docs](https://www.graphiti.dev/guides/getting-started/installation#adding-to-an-existing-app), maybe as a subsection, so users know to create the file and what it holds. We can always automate it later. Sound good?
